### ISSUE TITLE
YAML interprets numbers as Fixnum (even with other characters)

### ISSUE THREAD

**Issue by corroded** [stephencelis/app#8]
Is app trying to be too smart here?

I have an ENV var: 

`ENV['TEST_NUMBER'] = "+1239798798"`

and the following settings.yml:

```
defaults: &defaults
  twilio:
    from_phone: <%= ENV['FROM_PHONE'] %>
    test_recipient: <%= ENV['TEST_NUMBER'] %>
....
```

in rails console, `ENV['TEST_NUMBER']` is evaluated as '+123978798' but `Settings.twilio.test_recipient` is just '123978798'.

Using ruby 1.9.3-p484, rails 3.2.11
